name: project_google
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.10.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4
  connectivity_plus: ^6.0.3
  flutter_native_splash: ^2.4.1
  url_launcher: ^6.3.0
  flutter_inappwebview: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0


flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: "assets/images/splash_logo.png"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true

flutter:
  uses-material-design: true

  # # Performance optimizations
  # assets:
  #   - assets/images/

